# Generated by Django 5.2.6 on 2025-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('url_stream', models.URLField(max_length=300)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
