# Generated by Django 5.2.6 on 2025-09-27 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('segmento', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AvisoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='avisos_adjuntos/')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='avisos.aviso')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='ENVIADA', max_length=20)),
                ('token_notificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
