# Generated by Django 5.2.6 on 2025-09-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
        ),
    ]
