# Generated by Django 5.2.6 on 2025-09-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_areacomun_imagen_areacomun_precio_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('MANTENIMIENTO', 'Mantenimiento'), ('EVENTO_ESPECIAL', 'Evento Especial')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('areas_afectadas', models.ManyToManyField(blank=True, help_text='Si no se selecciona ninguna, afecta a todas', to='areas.areacomun')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('slots_por_hora', models.IntegerField(default=1, help_text='Número de reservas simultáneas permitidas')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='areas.areacomun')),
            ],
            options={
                'unique_together': {('area', 'dia_semana')},
            },
        ),
    ]
