# Generated by Django 5.2.6 on 2025-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_fechaespecial_horarioarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioarea',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioarea',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
