# Generated by Django 5.2.6 on 2025-09-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_multa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuota_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cuotaservicio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.unidad')),
            ],
        ),
    ]
